FROM node:14.18.2

WORKDIR /kochipad

COPY ./kochipad/package.json ./

# next canary
RUN yarn global add next@canary
RUN yarn

COPY ./kochipad/ ./

RUN rm -R ./pages

COPY ./kochipad/pages/avatar/ ./pages
COPY ./kochipad/pages/_app.js ./pages
COPY ./kochipad/pages/_document.js ./pages

RUN npm run build

VOLUME ["/kochipad/node_modules"]

CMD ["npm", "run", "dev"]
